Repository elastic/elastic-serverless-forwarder, pull requests merged in 2025-05, with the labels that each got.

#892 [docs] Add `products` to `docset.yml`
  docs/docset.yml
Labels: documentation, Team:Docs, docs

#899 Release v1.20.0
  CHANGELOG.md
  docs/reference/aws-deploy-elastic-serverless-forwarder.md
  share/version.py
Labels: Team:obs-ds-hosted-services

#901 [docs] Add note about Python 3.12 for Terraform users
  CHANGELOG.md
  docs/reference/aws-deploy-elastic-serverless-forwarder.md
Labels: Team:obs-ds-hosted-services

#904 Release v1.20.1
  CHANGELOG.md
  docs/reference/aws-deploy-elastic-serverless-forwarder.md
  share/version.py
Labels: Team:obs-ds-hosted-services, release
